# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
