# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='colors',
            field=models.CharField(default='', max_length=155),
        ),
    ]
